### ISSUE TITLE
(Greenfor branch) NATO SF support bar fails to increase

### ISSUE THREAD

**Issue by haserd2** [DukeVenator/A3-AntiStaki#3]
Upon testing the new OPTRE antistasi port we noticed that shooting down enemy aircraft, failing tasks, etc. fails to increase the NATO sf support number does not increase. The message instead pops up saying " NATO SF +0 "

Mods: OPTRE
OPCAN 2.0 by LM mods
CBA A3
CUP Terrains core
CUP Terrains Maps
OPCAN Terrains
Enhanced Movement
OPTRE FC

**Comment by DukeVenator** [comment]
Code that is problematic has been found 
working on a fix
